### ISSUE TITLE
Cabinet with more than one file inside

### ISSUE THREAD

**Issue by honza-kasik** [v3l0c1r4pt0r/xSDM#4]
Hello, i tried to download a file using your software and then this mesage appeared... Nice work btw :+1:

%DEBUG_START%
edv: '224922653^^WmxvFwH9yCiwSTtrWJOgc5IloiLVl7b8Pa1DKn9z4gDnG2d44Pvou2QDCDE1ZGGi75576759'
header:
0000:	0xCA 0x51 0x53 0x10 0x96 0x44 0xDA 0xFD 
0008:	0x00 0xAA 0xD9 0xA1 0xDC 0xE1 0xC4 0xAB 
0010:	0xF1 0x26 0xA4 0xB0 0xA7 0xBC 0x05 0x10 
0018:	0xBC 0x49 0x3B 0x54 0x7C 0x3E 0x24 0x48 
0020:	0xF7 0xDB 0x07 0x0A 0x99 0xB6 0x77 0x36 
0028:	0x03 0x5E 0xCF 0x90 0x97 0x9F 0xC2 0x88 
0030:	0x0F 0x7D 0x15 0x0F 0x00 0x25 0x39 0x23 
0038:	0x57 0xBD 0x51 0x4D 0x98 0x7F 0xF8 0xC2 
0040:	0x1B 0x03 0xF1 0x43 0x44 0xA3 0xEA 0xAD 
0048:	0xBC 0x01 0x65 0x9C 0x86 0x61 0xB2 0x09 
0050:	0x32 0xFC 0xDC 0x64 0xD8 0xB7 0xE1 0xE7 
0058:	0xAF 0xFF 0xF1 0x04 0x65 0x55 0x93 0xFC 
0060:	0x66 0x5B 0x7A 0x0D 0xF2 0x9E 0x34 0x40 
0068:	0x58 0x67 0x36 0x17 0xBD 0x11 0x56 0x85 
0070:	0x0F 0x08 0x9F 0xF2 0x85 0x30 0xCF 0xD4 
0078:	0x98 0x58 0x1A 0x95 0x94 0xB1 0xE2 0x99 
0080:	0xD6 0x6E 0x5F 0x86 0x7A 0x47 0x75 0x41 
0088:	0x89 0x1B 0x83 0xFE 0x27 0x50 0xEB 0xF0 
0090:	0x8C 0xBB 0x26 0xAC 0x36 0x19 0x10 0xC3 
0098:	0x7C 0x68 0x46 0x7A 0x40 0xB3 0x5F 0x65 
00A0:	0x52 0xEC 0x3E 0x9D 0x09 0x54 0xE9 0x1F 
00A8:	0x8A 0xFF 0xBF 0x74 0x39 0xE5 0x3C 0x0F 
00B0:	0xF0 0x1C 0xD2 0x7B 0x03 0xD2 0x24 0xB2 
00B8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00C0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00C8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00D0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00D8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00E0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00E8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00F0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
00F8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0100:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0108:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0110:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0118:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0120:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0128:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0130:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0138:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0140:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0148:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0150:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0158:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0160:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0168:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0170:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0178:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0180:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0188:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0190:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
0198:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01A0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01A8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01B0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01B8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01C0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01C8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01D0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01D8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01E0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01E8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01F0:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
01F8:	0x7A 0x2B 0x60 0x26 0xE5 0xFB 0x6D 0xCC 
%DEBUG_END%

**Comment by GMMan** [comment]
@honza-kasik If you're still watching this thread, mind posting the first 1 MiB of the file? I can probably check out the header and see if there's something new. I've recently downloaded Windows 10 Preview and didn't have problems extracting with my own unpacker.

**Comment by halorhhr** [comment]
got the same message on another package i think:

~/MSDN/APPS # xsdm -vf de_forefront_security_for_exchange_server_with_service_pack_1_x64_cd_x14-04703.sdc
Opening SDC file...             [OK]
Verifying keyfile...            [OK]
Validating SDC header...        [FAIL]
xsdm: File given is not valid SDC file or decryption key wrong
[OK]
%DEBUG_START%
edv: '3705505849^^yq8qqG9f4uVxGztTM1lK9v773GvGGanTIGRRCMK6qL2yvsnwWGLL83Hndt8zKeM425244378'
header:
0000:   0x64 0x77 0x53 0x30 0xC4 0x60 0x1A 0x7B
0008:   0x6A 0x1F 0xE5 0x39 0xD9 0x80 0xA5 0xFE
0010:   0x77 0x45 0x04 0xF3 0x68 0x22 0x3E 0x88
0018:   0xE0 0xFF 0xDD 0xF0 0xA5 0xEA 0xB4 0x1D
0020:   0x80 0xAD 0xCD 0x66 0x58 0xE8 0xD2 0x0A
0028:   0xB8 0x0C 0xFB 0xEB 0xA0 0xB1 0x2C 0x3D
0030:   0x21 0x30 0x1B 0xCB 0xBE 0xE7 0xBC 0x74
0038:   0x4E 0x12 0x39 0x76 0xEF 0x84 0xC9 0x98
0040:   0x67 0xC2 0xB9 0xDC 0x37 0x1F 0x24 0x6C
0048:   0x96 0x74 0xB5 0xAC 0x6B 0x9F 0x50 0xA3
0050:   0xD0 0xD2 0xAA 0x7A 0xAE 0x38 0xBA 0xAA
0058:   0x5D 0xDA 0x7C 0x24 0xD7 0x93 0x01 0xCD
0060:   0xB4 0x69 0xF7 0x22 0x7D 0x28 0x5D 0xA0
0068:   0x9A 0x06 0xCA 0xBA 0x92 0x06 0x64 0x32
0070:   0x5B 0x4C 0x85 0xDA 0x33 0x88 0x91 0x06
0078:   0x47 0xF7 0x9B 0xEF 0x6E 0xB5 0xE5 0x77
0080:   0x90 0x62 0xF0 0x7B 0x39 0xE6 0x4B 0xC2
0088:   0x64 0x6E 0x4A 0x55 0x60 0x30 0xFB 0x3B
0090:   0x6E 0xD2 0x52 0x67 0x84 0x38 0xA7 0x70
0098:   0x6A 0x1C 0xC5 0x13 0x4F 0x52 0x18 0x9F
00A0:   0x71 0x1B 0xF2 0x60 0x19 0x2B 0xFC 0x01
00A8:   0x74 0x18 0x51 0x8F 0x73 0xDB 0x52 0x9D
00B0:   0x25 0x79 0xC1 0x43 0x53 0xC0 0x31 0x38
00B8:   0x98 0xB7 0xCC 0x0C 0xF9 0x40 0xF1 0xB3
00C0:   0x1C 0x7F 0xB6 0xE6 0x3F 0xDA 0x0B 0x97
00C8:   0xC1 0xBD 0xD2 0x10 0xDC 0x30 0x95 0xE8
00D0:   0xD4 0x76 0x1B 0xE1 0x9B 0x71 0xC7 0x86
00D8:   0x49 0x3E 0x25 0x85 0xEA 0xDF 0x0C 0xAD
00E0:   0x77 0x51 0x2E 0x44 0x8B 0xA9 0x4E 0xAB
00E8:   0x29 0xA4 0x8E 0x19 0xA3 0x21 0x96 0xC6
00F0:   0xD0 0xB8 0x06 0xFB 0xE3 0xC5 0x56 0x2E
00F8:   0xDF 0x5C 0x71 0x03 0xB1 0x4F 0xEF 0x4A
0100:   0x52 0x5B 0x0C 0x20 0x02 0x16 0xA9 0xAA
0108:   0xE1 0xBB 0x66 0xBA 0xE6 0x4C 0x76 0x48
0110:   0x25 0xAE 0xA1 0xD9 0xB2 0xAC 0xFE 0x7F
0118:   0x2E 0xB4 0x71 0xD0 0xFE 0x73 0x6F 0x65
0120:   0x1D 0x1E 0x5E 0xF1 0xCD 0xBF 0x21 0xCB
0128:   0xEC 0x40 0x94 0xBA 0x74 0x53 0x12 0x54
0130:   0x1C 0x19 0x46 0x01 0xE1 0x67 0x15 0x3D
0138:   0xEE 0x98 0xC8 0x6C 0xB0 0x47 0xE9 0x4D
0140:   0x89 0x47 0xC8 0x2D 0x17 0xDE 0x85 0x91
0148:   0xB8 0xC1 0x2F 0x8E 0x01 0x15 0x96 0x47
0150:   0x01 0x36 0x46 0x9C 0x5B 0x9E 0xE9 0x59
0158:   0x71 0x56 0x0C 0x5A 0x8E 0x1D 0x50 0xC3
0160:   0x92 0xE7 0x7D 0x7F 0x01 0x2C 0x71 0xDB
0168:   0xF3 0xBD 0x0D 0x76 0x2F 0x67 0x57 0x8C
0170:   0x6B 0xF7 0xF5 0x75 0xFB 0x0A 0x55 0xF2
0178:   0x3F 0x37 0xD3 0x28 0xD4 0x31 0x00 0x1B
0180:   0x24 0xD6 0x14 0xF0 0x97 0x1E 0x50 0x1C
0188:   0x15 0xD9 0x90 0x98 0x70 0xA7 0xA1 0xA5
0190:   0x56 0x65 0x35 0x8B 0xDC 0xA3 0x55 0x52
0198:   0xAF 0x07 0x90 0xAD 0xBD 0x5B 0xC6 0x71
01A0:   0x59 0xF9 0x1F 0x54 0xB1 0x54 0x38 0xF2
01A8:   0x47 0x50 0x46 0x87 0xBF 0xE2 0x35 0x49
01B0:   0x3F 0x14 0xD9 0xDA 0xEF 0xF7 0x38 0x43
01B8:   0x73 0x3E 0x1A 0xDF 0x5A 0x71 0x18 0x82
01C0:   0x9E 0x66 0x01 0x54 0x7E 0xB1 0x12 0xE9
01C8:   0xAA 0x15 0x2B 0xA1 0x88 0x23 0x21 0xBA
01D0:   0x59 0xB0 0x6C 0x15 0x21 0x9F 0x6B 0x73
01D8:   0x62 0xB0 0x3C 0x2B 0x02 0xC1 0x10 0x8C
01E0:   0x7B 0x18 0xC8 0x6D 0xA3 0x37 0x3F 0x22
01E8:   0xCD 0xD9 0xB7 0xC6 0x86 0xB5 0x6A 0x00
01F0:   0xE4 0x35 0xB4 0xDC 0x6A 0xD7 0x0B 0x21
01F8:   0xB0 0x9C 0x2B 0x75 0xFE 0x4B 0xF4 0xD8
%DEBUG_END%
xsdm: Warning! You have encountered cabinet with more than one file inside. This is known problem since the program is now able to unpack only first.
 Please help improving the program by opening issue on github and paste above debug information. Thank you.
xsdm: crc32: 0x05F66AB0; orig: 0xDCDD8839
Checking file integrity...      [FAIL]
xsdm: CRC32 of sdc file did not match the one supplied in keyfile (0xDCDD8839 expected while have 0x5F66AB0)
Segmentation fault

**Comment by halorhhr** [comment]
and another one:
```
 xsdm -vf en_xna_game_studio_4.0_refresh_x86.sdc
Opening SDC file...             [OK]
Verifying keyfile...            [OK]
Validating SDC header...        [FAIL]
xsdm: File given is not valid SDC file or decryption key wrong
[OK]
%DEBUG_START%
edv: '2241655992^^nKzUEZtEDvqqdE84dDSdfF9bUDMpsG9NvsflHdxK2zpKqWGEkEjvLAtbzHAzY8yD53747571'
header:
0000:   0xD1 0x00 0x00 0x00 0xF1 0x6B 0x00 0x00
0008:   0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0010:   0x20 0x00 0x00 0x00 0x1F 0x93 0x63 0x7D
0018:   0xB4 0x24 0xCD 0x01 0x1F 0x93 0x63 0x7D
0020:   0xB4 0x24 0xCD 0x01 0x20 0xC7 0xF7 0x9A
0028:   0xB4 0x24 0xCD 0x01 0x1B 0x40 0x8C 0x02
0030:   0x00 0x00 0x00 0x00 0x08 0x31 0x8D 0x02
0038:   0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0040:   0x00 0x00 0x00 0x00 0x56 0x00 0x00 0x00
0048:   0x20 0x00 0x00 0x00 0x3B 0xAF 0xAE 0x4E
0050:   0xB5 0x24 0xCD 0x01 0x3B 0xAF 0xAE 0x4E
0058:   0xB5 0x24 0xCD 0x01 0x90 0x53 0x23 0x4F
0060:   0xB5 0x24 0xCD 0x01 0x80 0x00 0x00 0x00
0068:   0x00 0x00 0x00 0x00 0x84 0x00 0x00 0x00
0070:   0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0078:   0x00 0x00 0x00 0x00 0xB0 0x00 0x00 0x00
0080:   0x7B 0x50 0xDB 0x2C 0xCC 0x64 0xF0 0x08
0088:   0x77 0x64 0x6F 0x5B 0xD5 0xA7 0xA4 0xB0
0090:   0x0F 0x38 0xDE 0xC1 0xD5 0x36 0x5D 0x0B
0098:   0xD2 0xDD 0x41 0xD5 0xA8 0x79 0xC7 0xDE
00A0:   0x41 0x69 0x7B 0xA2 0xC6 0x76 0x04 0x8E
00A8:   0xF0 0x28 0x7C 0x9C 0xD5 0x96 0x50 0xD8
00B0:   0x15 0xF6 0x13 0x98 0x51 0xDC 0x8A 0x78
00B8:   0xC3 0xFB 0x05 0x3A 0x40 0xC3 0x68 0x8D
00C0:   0xE0 0xDE 0x29 0x3C 0x67 0x01 0x04 0x60
00C8:   0x36 0x7E 0xEE 0xE2 0xE2 0xE6 0x1D 0x20
00D0:   0x40 0xD9 0xB6 0x9F 0x31 0x86 0x2F 0xA2
00D8:   0x59 0x18 0x09 0x52 0x3A 0x61 0x57 0xFB
00E0:   0x8F 0x18 0x11 0xEE 0x43 0x03 0x46 0x1F
00E8:   0xC3 0x6E 0x1B 0x61 0x81 0x51 0x9B 0x69
00F0:   0xEF 0xF8 0x53 0x41 0xAB 0xCB 0x7E 0x6C
00F8:   0xB0 0xA4 0xD3 0x3C 0x68 0x27 0x46 0xFA
0100:   0x0B 0x3D 0xAD 0xA3 0x9C 0x36 0x89 0xEE
0108:   0x25 0x57 0x90 0xBB 0x0A 0x32 0x7B 0x7A
0110:   0x6C 0xDF 0x7C 0x59 0xA4 0xE3 0x3D 0xE7
0118:   0xD8 0xF0 0x22 0xCE 0x5F 0x89 0x84 0x21
0120:   0xE6 0x4F 0x83 0x47 0x5B 0xE5 0x7F 0xC5
0128:   0x64 0xC6 0x2B 0x54 0xFE 0x4C 0x95 0xE4
0130:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0138:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0140:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0148:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0150:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0158:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0160:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0168:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0170:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0178:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0180:   0x00 0x00 0x00 0x00 0x00 0x00 0xD3 0xC5
0188:   0x80 0x4F 0x66 0xCD 0xE9 0xDF 0x86 0xB1
0190:   0xAD 0xB5 0xB9 0x8B 0x26 0x8A 0x69 0x1A
0198:   0x42 0xFA 0xD2 0x53 0xFA 0x4A 0x8D 0x16
01A0:   0x29 0xF1 0xDF 0x14 0xB2 0x82 0x02 0xA6
01A8:   0x4E 0x06 0x11 0xE0 0x5F 0x94 0x99 0x2E
01B0:   0xAF 0x14 0x98 0xD0 0x44 0xA5 0x61 0xAB
01B8:   0x6F 0x31 0x9F 0xC3 0x66 0xB8 0x51 0x57
01C0:   0xB8 0x82 0x22 0x90 0xFE 0x8A 0x62 0xAC
01C8:   0xC0 0xE4 0x60 0x48 0x07 0x78 0xE7 0x61
01D0:   0x2D 0x58 0x98 0x36 0x8E 0xD7 0x78 0xB7
01D8:   0x78 0x6A 0xFA 0x71 0x5F 0xCB 0xB0 0x25
01E0:   0xBE 0x11 0xB4 0x31 0xFB 0x92 0x3E 0x91
01E8:   0x8E 0xCA 0x86 0xB9 0x24 0x19 0x4E 0x1D
01F0:   0xD0 0xA7 0x4A 0x6F 0x16 0x34 0xF5 0xF8
01F8:   0x22 0xFF 0x65 0x9D 0x4B 0x77 0x7E 0x98
%DEBUG_END%
xsdm: Warning! You have encountered cabinet with more than one file inside. This is known problem since the program is now able to unpack only first.
 Please help improving the program by opening issue on github and paste above debug information. Thank you.
xsdm: crc32: 0x859CF4B8; orig: 0x859CF4B8
Checking file integrity...      [OK]
Decoding file name...           [OK]
File path: C▒يv8▒%▒▒:{▒Y▒8▒▒▒O▒▒g▒+&)7.▒XA▒4▒J▒ވ*▒s`    ǖ#▒
\XNA Game Studio 4.0 Refresh (x8
Creating directory structure... [OK]
File has been originally created at 2012/04/27 21:05:48, last accessed at 2012/04/27 21:05:48 and modified at 2012/04/27 21:06:37
file size has been set as 42807560 (0x28D3108), signature: 0xD1
PuTTYUnpacking file(s)...               [OK]

0000:   0xD1 0x00 0x00 0x00 0xF1 0x6B 0x00 0x00
0008:   0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0010:   0x20 0x00 0x00 0x00 0x1F 0x93 0x63 0x7D
0018:   0xB4 0x24 0xCD 0x01 0x1F 0x93 0x63 0x7D
0020:   0xB4 0x24 0xCD 0x01 0x20 0xC7 0xF7 0x9A
0028:   0xB4 0x24 0xCD 0x01 0x1B 0x40 0x8C 0x02
0030:   0x00 0x00 0x00 0x00 0x08 0x31 0x8D 0x02
0038:   0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0040:   0x00 0x00 0x00 0x00 0x56 0x00 0x00 0x00
0048:   0x43 0xD9 0x05 0xD9 0x8A 0x76 0x38 0x94
0050:   0x25 0xB2 0x0E 0xD2 0x3A 0x7B 0xCA 0x59
0058:   0xED 0x38 0x85 0xA3 0xA3 0x4F 0xEB 0xF0
0060:   0x67 0xE1 0xA1 0x2B 0x26 0x29 0x37 0x2E
0068:   0xBC 0x58 0x41 0xDA 0x03 0x34 0x88 0x4A
0070:   0xE1 0x99 0xDE 0x88 0x2A 0xE7 0x73 0x60
0078:   0x09 0xC7 0x96 0x23 0x35 0x08 0xF6 0x0A
0080:   0x2F 0x58 0x4E 0x41 0x20 0x47 0x61 0x6D
0088:   0x65 0x20 0x53 0x74 0x75 0x64 0x69 0x6F
0090:   0x20 0x34 0x2E 0x30 0x20 0x52 0x65 0x66
0098:   0x72 0x65 0x73 0x68 0x20 0x28 0x78 0x38
00A0:   0x41 0x69 0x7B 0xA2 0xC6 0x76 0x04 0x8E
00A8:   0xF0 0x28 0x7C 0x9C 0xD5 0x96 0x50 0xD8
00B0:   0x15 0xF6 0x13 0x98 0x51 0xDC 0x8A 0x78
00B8:   0xC3 0xFB 0x05 0x3A 0x40 0xC3 0x68 0x8D
00C0:   0xE0 0xDE 0x29 0x3C 0x67 0x01 0x04 0x60
00C8:   0x36 0x7E 0xEE 0xE2 0xE2 0xE6 0x1D 0x20
00D0:   0x40 0xD9 0xB6 0x9F 0x31 0x86 0x2F 0xA2
00D8:   0x59 0x18 0x09 0x52 0x3A 0x61 0x57 0xFB
00E0:   0x8F 0x18 0x11 0xEE 0x43 0x03 0x46 0x1F
00E8:   0xC3 0x6E 0x1B 0x61 0x81 0x51 0x9B 0x69
00F0:   0xEF 0xF8 0x53 0x41 0xAB 0xCB 0x7E 0x6C
00F8:   0xB0 0xA4 0xD3 0x3C 0x68 0x27 0x46 0xFA
0100:   0x0B 0x3D 0xAD 0xA3 0x9C 0x36 0x89 0xEE
0108:   0x25 0x57 0x90 0xBB 0x0A 0x32 0x7B 0x7A
0110:   0x6C 0xDF 0x7C 0x59 0xA4 0xE3 0x3D 0xE7
0118:   0xD8 0xF0 0x22 0xCE 0x5F 0x89 0x84 0x21
0120:   0xE6 0x4F 0x83 0x47 0x5B 0xE5 0x7F 0xC5
0128:   0x64 0xC6 0x2B 0x54 0xFE 0x4C 0x95 0xE4
0130:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0138:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0140:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0148:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0150:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0158:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0160:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0168:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0170:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0178:   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
0180:   0x00 0x00 0x00 0x00 0x00 0x00 0xD3 0xC5
0188:   0x80 0x4F 0x66 0xCD 0xE9 0xDF 0x86 0xB1
0190:   0xAD 0xB5 0xB9 0x8B 0x26 0x8A 0x69 0x1A
0198:   0x42 0xFA 0xD2 0x53 0xFA 0x4A 0x8D 0x16
01A0:   0x29 0xF1 0xDF 0x14 0xB2 0x82 0x02 0xA6
01A8:   0x4E 0x06 0x11 0xE0 0x5F 0x94 0x99 0x2E
01B0:   0xAF 0x14 0x98 0xD0 0x44 0xA5 0x61 0xAB
01B8:   0x6F 0x31 0x9F 0xC3 0x66 0xB8 0x51 0x57
01C0:   0xB8 0x82 0x22 0x90 0xFE 0x8A 0x62 0xAC
01C8:   0xC0 0xE4 0x60 0x48 0x07 0x78 0xE7 0x61
01D0:   0x2D 0x58 0x98 0x36 0x8E 0xD7 0x78 0xB7
01D8:   0x78 0x6A 0xFA 0x71 0x5F 0xCB 0xB0 0x25
01E0:   0xBE 0x11 0xB4 0x31 0xFB 0x92 0x3E 0x91
01E8:   0x8E 0xCA 0x86 0xB9 0x24 0x19 0x4E 0x1D
01F0:   0xD0 0xA7 0x4A 0x6F 0x16 0x34 0xF5 0xF8
01F8:   0x22 0xFF 0x65 0x9D 0x4B 0x77 0x7E 0x98
```

**Comment by v3l0c1r4pt0r** [comment]
@halorhhr the first sample you provided seems to be broken file, so check if your download didn't fail and if you provided decryption key of the file you downloaded. 
The second sample seems to be valid so I will try to confirm that it is really two-file archive ASAP. Thanks for your help.

**Comment by halorhhr** [comment]
@v3l0c1r4pt0r i tried redownloading the first package but still get the same output. Maybe the package is damaged serverside anyway.
I also got couple other files with same or similar problems, tell me if you need them too.

**Comment by v3l0c1r4pt0r** [comment]
Note for everyone, who has any problem with xsdm: Try using method described in #13. By the way report your problem, too!
