### ISSUE TITLE
Problem with unpacking by SDM

### ISSUE THREAD

**Issue by RadekSimkanic** [v3l0c1r4pt0r/xSDM#6]
```
$ xsdm '/home/gulliver/Python/SDM Downloader/SDC/1.sdc' 
Opening SDC file...		[OK]
[FAIL]
/home/gulliver/Python/SDM Downloader/SDC/1.sdc.key: No such file or directory
```
The file have 3.6 GB (en_windows_8_1_x64_dvd). This file has been from two files via dd.

**Comment by v3l0c1r4pt0r** [comment]
At first I doubt that combining the files can even work some way, because they two separate archives. You should not merge them. 
Are you sure that 1.sdc.key exists? And even when you do it right I'm afraid that recently Microsoft was doing something bad with the format or in my program is a bug that, at least in my case, is preventing me from unpacking Windows 8 image. If I am right debugging will be necessary and I'm afraid I couldn't do it soon.
Nevertheless try to do what I've written above and tell me if it failed or not.

**Comment by RadekSimkanic** [comment]
Solved. I had 1.key instead of 1.sdc.key :D . Sorry for the inconvenience.
